export const IPC_CHANNELS = {
	GET_APP_DATA_PATH: 'getAppDataPath',
	JOIN_PATH: 'joinPath',
	READ_FILE: 'readfile',
	WRITE_FILE: 'writefile',
	DELETE_FILE: 'deletefile',
	LIST_FILES: 'listFiles',
	CREATE_DIRECTORY_IF_NOT_EXISTS: 'createDirectoryIfNotExists',
	SHOW_SAVE_DIALOG: 'showSaveDialog',
	SAVE_SETTINGS_ZIP: 'saveSettingsZip',
	FLASH_WINDOW: 'flashWindow',
	START_EXPRESS_SERVER: 'startExpressServer',
	ON_OSU_OAUTH_CODE: 'onOsuOauthCode',
	OPEN_LINK: 'openLink',
	CHECK_FOR_UPDATES_AND_NOTIFY: 'checkForUpdatesAndNotify',
	UPDATE_AVAILABLE: 'update-available',
	UPDATE_DOWNLOADED: 'update-downloaded',
	UPDATE_ERROR: 'error',
	RESTART_APP_AFTER_UPDATE_DOWNLOAD: 'restartAppAfterUpdateDownload',
	UPDATE_DOWNLOAD_PROGRESS: 'download-progress',
	GET_ALL_IRC_CHANNELS: 'getAllIrcChannels',
	GET_IRC_CHANNEL: 'getIrcChannel',
	SET_ALL_IRC_CHANNELS: 'setAllIrcChannels',
	SET_IRC_CHANNEL: 'setIrcChannel',
	DELETE_IRC_CHANNEL: 'deleteIrcChannel',
	ADD_OUTGOING_IRC_MESSAGE: 'addOutgoingIrcMessage',
	ADD_IRC_MESSAGE: 'addIrcMessage',
	CHANGE_LAST_ACTIVE_CHANNEL: 'changeLastActiveChannel',
	CHANGE_ACTIVE_CHANNEL: 'changeActiveChannel',
	SET_IRC_PLAY_SOUND_ON_MESSAGE: 'setIrcPlaySoundOnMessage',
	SET_IRC_CHANNEL_LABEL: 'setIrcChannelLabel'
} as const;

export type IpcChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS];
