export const IPC_CHANNELS = {
	CHECK_FOR_MIGRATIONS_AND_NOTIFY: 'checkForMigrationsAndNotify',
	RESTART_APP_AFTER_MIGRATION: 'restartAppAfterMigration',
	MIGRATION_NEEDED: 'migrationNeeded',
	START_DATA_MIGRATION: 'startDataMigration',
	GET_APP_DATA_PATH: 'getAppDataPath',
	JOIN_PATH: 'joinPath',
	READ_FILE: 'readfile',
	WRITE_FILE: 'writefile',
	DELETE_FILE: 'deletefile',
	LIST_FILES: 'listFiles',
	CREATE_DIRECTORY_IF_NOT_EXISTS: 'createDirectoryIfNotExists',
	SHOW_SAVE_DIALOG: 'showSaveDialog',
	SAVE_SETTINGS_ZIP: 'saveSettingsZip',
	FLASH_WINDOW: 'flashWindow',
	START_EXPRESS_SERVER: 'startExpressServer',
	ON_OSU_OAUTH_CODE: 'onOsuOauthCode',
	OPEN_LINK: 'openLink',
	CHECK_FOR_UPDATES_AND_NOTIFY: 'checkForUpdatesAndNotify',
	UPDATE_AVAILABLE: 'update-available',
	UPDATE_DOWNLOADED: 'update-downloaded',
	UPDATE_ERROR: 'error',
	RESTART_APP_AFTER_UPDATE_DOWNLOAD: 'restartAppAfterUpdateDownload',
	UPDATE_DOWNLOAD_PROGRESS: 'download-progress',
	CREATE_IRC_CHANNEL: 'createIrcChannel',
	DELETE_IRC_CHANNEL: 'deleteIrcChannel',
	GET_ALL_IRC_CHANNELS: 'getAllIrcChannels',
	GET_IRC_CHANNEL: 'getIrcChannel',
	SET_IRC_CHANNEL_LABEL: 'setIrcChannelLabel',
	SET_IRC_PLAY_SOUND_ON_MESSAGE: 'setIrcPlaySoundOnMessage',
	CHANGE_ACTIVE_CHANNEL: 'changeActiveChannel',
	CHANGE_LAST_ACTIVE_CHANNEL: 'changeLastActiveChannel',
	ADD_IRC_MESSAGE: 'addIrcMessage',
	ADD_OUTGOING_IRC_MESSAGE: 'addOutgoingIrcMessage',
	GET_IRC_CREDENTIALS: 'getIrcCredentials',
	GET_IRC_USERNAME: 'getIrcUsername',
	GET_API_KEY: 'getApiKey',
	SET_API_KEY: 'setApiKey',
	SET_IRC_LOGIN: 'setIrcLogin',
	CLEAR_IRC_LOGIN: 'clearIrcLogin',
	CLEAR_API_KEY: 'clearApiKey'
} as const;

export type IpcChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS];
