name: 'Build releases'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-2019
        node_version: [16.x]
    name: Node ${{ matrix.node_version }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install

      - name: Checking linter
        run: yarn run lint

      - if: runner.os == 'Linux'
        name: Building release for Linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run gh-publish-linux

      - if: runner.os == 'Windows'
        name: Building release for Windows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run gh-publish-windows

      - if: runner.os == 'macOs'
        name: Building release for macOS
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run gh-publish-mac
